[package]
name = "example-tui"
edition = "2024"
version = "0.0.0"
categories = ["development-tools"]
homepage = "https://github.com/aspect-build/aspect-cli"
repository = "https://github.com/aspect-build/aspect-cli"
license = "Apache 2"
readme = "README.md"
rust-version = "1.88.0"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = "debuginfo"

[dependencies]
anes = "0.2.1"
anyhow = "1.0.99"
crossterm = "0.28.1"
once_cell = "1.21.3"
peak_alloc = "0.3.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tui-big-text = "0.7.1"

[patch.crates-io]
crossterm = { git = "https://github.com/thesayyn/crossterm", branch = "master" }
