[package]
name = "aspect-cli"
version.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
rust-version.workspace = true
default-run = "aspect-cli"


[[bin]]
name = "aspect-cli"
path = "src/main.rs"

[dependencies]
aspect-telemetry = { path = "../aspect-telemetry" }
axl-runtime = { path = "../axl-runtime" }
clap = {version= "4.5.40", features = ["string"]}
miette = { version = "7.6.0", features = ["fancy"] }
opentelemetry = "0.31.0"
opentelemetry_sdk = "0.31.0"
opentelemetry-otlp = {version = "0.31.0", features = ["grpc-tonic", "tls-roots"]}
opentelemetry-semantic-conventions = "0.31.0"
reqwest = { version = "0.12.22", default-features = false, features = ["http2", "charset", "system-proxy", "rustls-tls", "stream"] }
starlark = "0.13.0"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["macros", "rt", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-core = "0.1.34"
# tracing-opentelemetry = "0.32.0"
tracing-opentelemetry = { git = "https://github.com/thesayyn/tracing-opentelemetry", branch = "v0.1.x"}
tracing-subscriber = "0.3.20"
