[aspect-cli]
version = "2025.46.6"
sources = [
   # Try to use cargo build for dogfooding
   { path = "target/debug/aspect-cli" },
   # Fall back to Bazel dev build
   { path = "bazel-bin/crates/aspect-cli/aspect-cli" },
   # Fall back to release version
   { org = "aspect-build", repo = "aspect-cli", release = "v{{ version }}", artifact = "aspect-cli-{{ llvm_triple }}" },
]
