[tools.cli]
version = "0.0.0-dev"
sources = [
   # Try to use a dev build for dogfooding
   { path = "bazel-bin/crates/aspect-cli/aspect-cli" },
   # Fallback to cargo
   { path = "target/debug/aspect-cli" },
   # Fall back to inrelease
   { org = "aspect-build", repo = "aspect-cli", release = "v{{ version }}", artifact = "aspect-cli-{{ bzlos }}_{{ bzlarch }}" },
]

[tools.bazelisk]
version = "1.26.0"
