name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  aspect-workflows:
    name: Aspect Workflows
    with:
      queue: aspect-cli
    uses: aspect-build/workflows-action/.github/workflows/aspect-workflows.yaml@5.5.0-rc0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate changed files
        if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'allow sdk change')
        run: ./.github/workflows/validate_changed_files.sh
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Bazel caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-repo
          key: bazel-cache-${{ hashFiles('**/*.go', '**/BUILD.bazel', '**/*.bzl', 'WORKSPACE') }}
          restore-keys: bazel-cache-
      - name: Go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod', '**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Tidy up repository
        run: ./.github/workflows/tidy_up_repository.sh
      - name: bazel test //...
        env:
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
