name: Publish Release

on:
  workflow_call:
    inputs:
      tag_name:
        description: 'The tag name for the release (e.g., v2024.1.0)'
        required: true
        type: string
  push:
    tags:
      - 'v202[0-9].[0-9]+.[0-9]+'

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build_release_artifacts:
    uses: ./.github/workflows/build_release_artifacts.yaml
  release:
    name: Build MacOS and Linux release artifacts
    runs-on: ubuntu-latest
    needs: build_release_artifacts
    steps:
      - uses: actions/checkout@v6
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Calculate shasum
        run: shasum -a 256 assets/* > sha256

      - name: Prepare workspace snippet
        env:
          TAG: ${{ inputs.tag_name || github.ref_name }}
        run: .github/workflows/install_snippet.sh > release_notes.txt

      - name: Create GitHub draft release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          body_path: release_notes.txt
          files: |
            assets/*
            sha256
